{
  localization {
    locales {
      code
      isBundled
      isSideloaded
      isRTL
      name
      nativeName
    }
    config {
      locale
      namespacing
      namespaces
      sideloadPath
    }
  }
}
