mutation($locale: String!, $namespacing: Boolean!, $namespaces: [String]!) {
  localization {
    updateLocale(locale: $locale, namespacing: $namespacing, namespaces: $namespaces) {
      responseResult {
        succeeded
        errorCode
        slug
        message
      }
    }
  }
}
