# ===============================================
# LOCALIZATION
# ===============================================

extend type Query {
  localization: LocalizationQuery
}

extend type Mutation {
  localization: LocalizationMutation
}

# -----------------------------------------------
# QUERIES
# -----------------------------------------------

type LocalizationQuery {
  locales: [LocalizationLocale]
  config: LocalizationConfig
  translations(locale: String!, namespace: String!): [Translation]
}

# -----------------------------------------------
# MUTATIONS
# -----------------------------------------------

type LocalizationMutation {
  updateLocale(
    locale: String!
    namespacing: Boolean!
    namespaces: [String]!
  ): DefaultResponse @auth(requires: ["manage:system"])
}

# -----------------------------------------------
# TYPES
# -----------------------------------------------

type LocalizationLocale {
  code: String!
  isBundled: Boolean!
  isSideloaded: Boolean!
  isRTL: Boolean!
  name: String!
  nativeName: String!
}

type LocalizationConfig {
  locale: String!
  namespacing: Boolean!
  namespaces: [String]!
  sideloadPath: String!
}

type Translation {
  key: String!
  value: String!
}
